### ISSUE TITLE
Can't compile on Xcode 7 beta

### ISSUE THREAD

**Issue by tomvanzummeren** [oarrabi/OALayoutAnchor#2]
A new feature in Xcode 7 / Swift 2 / iOS 9 is that it compile-time checks whether you can call certain API's, including the UILayoutAnchor stuff.

So when I try to use OALayoutAnchor, which conforms to exactly the same API as the UILayoutAnchor, it (incorrectly) complains about topAnchor only being available from iOS 9...

![only available on iOS 9.0 or newer](https://cloud.githubusercontent.com/assets/188839/8372750/67efb94c-1be6-11e5-8823-22589ad0c779.png)

**Comment by nsomar** [comment]
Hey,

I introduced a temporary solution for making this work in swift.

Since anchor UIView's properties are annotated with `NS_AVAILABLE_IOS(9_0);`, it makes them unusable with swift when the app deployment target is less than iOS9.
The compiler will not allow the usage of anchor properties without guarding against the iOS version.

```
if #available(iOS 9.0, *) {
    view.leftAnchor
} else {
    // Fallback on earlier versions
}
```

In order to target this problem, `OALayoutAnchor` contains a mirror of all the anchor properties. these properties are named with a prefix of `oa_`

```
var oa_leadingAnchor: NSLayoutXAxisAnchor! { get }
var oa_trailingAnchor: NSLayoutXAxisAnchor! { get }
var oa_leftAnchor: NSLayoutXAxisAnchor! { get }
... etc..
```

As an example, using `oa_leadingAnchor` in iOS 9 and up, will forward the invocation to `leadingAnchor`. On iOS 8 and 7, this call will use the layout anchor from `OALayourAnchor`.

`NSLayoutConstraint` `active` property is also unusable in swift for any iOS less than 8. In order to address this issue please use `oa_active`.
Using `oa_active` will result in using `active` on iOS 8,9 and doing nothing on iOS 7.

This is an example in swift:

```
view1.oa_widthAnchor.constraintEqualToConstant(100).oa_active = true
view1.oa_heightAnchor.constraintEqualToConstant(100).oa_active = true
view1.oa_centerXAnchor.constraintEqualToAnchor(self.view.oa_centerXAnchor).oa_active = true
view1.oa_centerYAnchor.constraintEqualToAnchor(self.view.oa_centerYAnchor).oa_active = true
```

Do you think this would help? what are your notes on this take?

**Comment by tomvanzummeren** [comment]
Yes, I think that will be the only solution that will do the trick! Nice work!

**Comment by nsomar** [comment]
Thanks :) I will close this for now.
